Add Stackbit
huangyz0918/moving pull request #18
Opened 2019-08-28 06:36 UTC by JugglerX

This pull request add's Stackbit to this theme. It add's the stackbit.yaml file which makes this theme work with several headless CMS automatically (including Forestry, NetlifyCMS, DatoCMS & Contentful) and it deploys the site to Netlify in 1 click.

You can try it out: https://app.stackbit.com/create?theme=https://github.com/stackbithq/moving (note the "create with stackbit" button in the readme will import the theme from your repo so until the PR is merged it wont work)

Hope you think it's as awesome as i do!

2019-08-28 07:41 UTC, huangyz0918 requested changes
Great feature @JugglerX, I have some tiny suggestions about your changes, please checkout and update. Thanks a lot.

2019-08-28 07:41 UTC, huangyz0918 commented on _includes/head.html
> +  <link rel="stylesheet" href="/assets/css/agate.css" />
Please keep the related path of your site, or it cannot find the .css files when deployed.

2019-08-28 07:41 UTC, huangyz0918 commented on moving.gemspec
> +  spec.add_development_dependency "bundler", "2.0.1"
Please keep bundled version ~> 2.0.2.

2019-08-28 07:41 UTC, huangyz0918 commented on README.md
> +This theme is ready to import into Stackbit in 1 click. This theme can be deployed to Netlify and you can connect any headless CMS including Forestry, NetlifyCMS, DatoCMS or Contentful.
Change 1 click to: single click.

2019-08-28 07:53 UTC, luhc228 commented
Please flx the ci error

2019-09-24 15:51 UTC, luhc228 commented
Please fix the conflict.

2021-02-16 01:17 UTC, closed without merging